import path from 'path';
import fs from 'fs';
import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import basicSsl from '@vitejs/plugin-basic-ssl';

export default defineConfig(({ mode }) => {
    const env = loadEnv(mode, '.', '');
    const HOST = env.VITE_HOST || '0.0.0.0';
    // Prefer using the project's `certs/localhost.crt` and `certs/localhost.key` (generated by backend's `generate-certs.js`) when available.
    // This ensures the certificate contains the IP SAN (e.g., 10.69.2.48) so https://10.69.2.48:3000 works in the browser.
    const certPath = path.resolve(__dirname, 'certs', 'localhost.crt');
    const keyPath = path.resolve(__dirname, 'certs', 'localhost.key');
    let httpsConfig: any = true;
    if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
      const certStat = fs.statSync(certPath);
      const keyStat = fs.statSync(keyPath);
      httpsConfig = {
        key: fs.readFileSync(keyPath),
        cert: fs.readFileSync(certPath),
      };
    } else {
      console.warn('⚠️');
    }

    // Diagnostic: print whether httpsConfig is an object or true
    console.log('vite https config type:', typeof httpsConfig === 'object' ? 'object' : String(httpsConfig));

    return {
      server: {
        port: 3000,
        host: HOST,
        https: httpsConfig,
      },
      plugins: [ ...(httpsConfig === true ? [basicSsl()] : []), react()],
      define: {
        'process.env.API_KEY': JSON.stringify(env.GEMINI_API_KEY),
        'process.env.VITE_API_URL': JSON.stringify(env.VITE_API_URL)
      },
      resolve: {
        alias: {
          '@': path.resolve(__dirname, '.'),
        }
      }
    };
});
